scan_for_lights:
  description: Scans the DALI bus for new lights and adds them to Home Assistant.
  fields: {}

broadcast_on:
  description: Turns on all lights on the DALI bus to their maximum level.
  fields: {}

broadcast_off:
  description: Turns off all lights on the DALI bus.
  fields: {}

set_fade_time:
  description: Sets the DALI fade time for all devices on the bus.
  fields:
    fade_time:
      description: A DALI fade code (0-15).
      example: 10
      selector:
        number:
          min: 0
          max: 15

export_names:
  description: |
    Export DALI address to name mappings to a JSON file.
    Each entry includes entity ID, unique ID, name, area, and device info.
  fields:
    path:
      description: Optional path within the Home Assistant config directory.
      example: foxtron_dali_names.json
      selector:
        text:

import_names:
  description: |
    Import DALI address to name mappings from a JSON file created by
    `export_names`. Restores name, area, and device name for matching entities.
  fields:
    path:
      description: Optional path within the Home Assistant config directory.
      example: foxtron_dali_names.json
      selector:
        text:
