name: pre-commit

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - id: changed-files
        uses: tj-actions/changed-files@v39
      - uses: pre-commit/action@v3.0.1
        if: steps.changed-files.outputs.all_changed_files != ''
        with:
          extra_args: --files ${{ steps.changed-files.outputs.all_changed_files }}
